### ISSUE TITLE
Bing translator doesn't work

### ISSUE THREAD

**Issue by ZhymabekRoman** [Animenosekai/translate#13]
```
>>> from translatepy.translators.bing import BingTranslate
>>> dl = BingTranslate()
>>> dl.translate("hello", "ru")
Traceback (most recent call last):
  File "/home/ubuntu/translate/translatepy/translators/base.py", line 60, in translate
    translation = self._translate(text, dest_code, source_code)
  File "/home/ubuntu/translate/translatepy/translators/bing.py", line 84, in _translate
    return response[0]["translations"][0]["text"]
KeyError: 0

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/translate/translatepy/translators/base.py", line 75, in translate
    raise TranslationError from exc
translatepy.exceptions.TranslationError
```

Server response: {'statusCode': 400}

**Comment by Animenosekai** [comment]
I just checked and yea it might be because they changed their API

**Comment by ZhymabekRoman** [comment]
Fixed in v2.0 alpha: https://github.com/ZhymabekRoman/translate/commit/80ce159757f1b6a5ac20c2559474f66cae8488b8
![image](https://user-images.githubusercontent.com/61125068/119853822-588f7a00-bf32-11eb-864f-28e55de46e5f.png)

**Comment by ZhymabekRoman** [comment]
> it might be because they changed their API
Yeah, they forbade accessing to the server without a key and token, I implemented parsing of the token, key, and other data as well as it was in old Yandex Translate implementation

**Comment by Animenosekai** [comment]
> > it might be because they changed their API
> 
> Yeah, they forbade accessing to the server without a key and token, I implemented parsing of the token, key, and other data as well as it was in old Yandex Translate implementation

Oh by parsing the website?

**Comment by ZhymabekRoman** [comment]
> Oh by parsing the website?

Yes, so far there are no other working methods

**Comment by NawtJ0sh** [comment]
Am getting this now with bing translate...
```
{u'errorMessage': u'', u'statusCode': 400}
```

**Comment by NawtJ0sh** [comment]
@Animenosekai Does anything from Bing work? Sorry I don't really use this translator.

**Comment by Animenosekai** [comment]
@NawtJ0sh Yes the actual version on `main` seems to work for now.

I'll publish translatepy v2 soon so it isn't available on PyPI for now but you can download the brand new version with git (look at the README for further information)
