### ISSUE TITLE
Error when translating long sentences

### ISSUE THREAD

**Issue by Vioshim** [Animenosekai/translate#2]
Good morning, well today I've been trying the module for my project and discovered a glitch of the application, which seems to happen in most strings.

Basically, It only translates the first line of a string.

I've tried to make workaround to it, by replacing the newlines with spaces, and even replacing the dots with commas, but it seems that it is still quite limited, in the sense that it doesn't translate text with more than 240+ ish.

This is a sample text
```
The Fusky entered into the library and breathed the tranquil atmosphere of the library, as well as the smell of old books.
"Nothing like a good old friend." He sighed and smiled. Even though he didn't particularly like the idea of being for hours and hours with his snout on some books... once again, but that was what he did, so he wouldn't stop now, would he?
When he reached the table he had left the books on some time ago, he blinked twice finding nothing there.        
"...That can be inconvenience."
He looked at his immediate surroundings and sighed in relief when he spotted those books on another table. When he reached this other table, he realized there was more books than those he had chosen before, and judging by the 
titles they were about Norwich's history itself.
He stood there with a wide and curious gaze, looking down at the books.
...Why would someone take my books when they were searching for the city's history...?
He shook his head and sat down on the table, placing the history books on the other side of it and focusing on the books he chose a while ago.
Now I have to organize them again...
He sighed and started working.
```

And it only translates this part
```
The Fusky entered into the library and breathed the tranquil atmosphere of the library, as well as the smell of old books.
```

This is how I use the translator
```py
text = "" #Big Paragraph
translator = Translator()
print(translator.translate(text=text, destination_language="Spanish").result)
```

Anyways thanks for the time, this project is quite amazing.

**Comment by Animenosekai** [comment]
Hello and thank you for using my module!

I investigated your issue and found that the result from Google Translate's API was a list of sentences!

I have successfully fixed the issue and the new version will soon be available on PyPI for you to update easily your current installation of `translatepy`!

New version: `v1.1`
