### ISSUE TITLE
gtoken is broken

### ISSUE THREAD

**Issue by ZhymabekRoman** [Animenosekai/translate#21]
```
python
Python 3.9.6 (default, Aug 12 2021, 05:34:51)
[Clang 9.0.8 (https://android.googlesource.com/toolchain/llvm-project 98c855489 on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from translatepy.utils.gtoken import TokenAcquirer
>>> acquirer = TokenAcquirer()
>>> tk = acquirer.do(text)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'text' is not defined
>>> text = "Hello"
>>> tk = acquirer.do(text)
Traceback (most recent call last):
  File "/data/sdext2/data/com.termux/files/home/git/translate/translatepy/utils/gtoken.py", line 106, in _update
    code = self.RE_TKK.search(r.text).group(1).replace('var ', '')
AttributeError: 'NoneType' object has no attribute 'group'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/sdext2/data/com.termux/files/home/git/translate/translatepy/utils/gtoken.py", line 242, in do
    self._update()
  File "/data/sdext2/data/com.termux/files/home/git/translate/translatepy/utils/gtoken.py", line 110, in _update
    raise Exception('Could not find TKK token for this request.\nSee https://github.com/ssut/py-googletrans/issues/234 for more details.')
Exception: Could not find TKK token for this request.
See https://github.com/ssut/py-googletrans/issues/234 for more details.
>>>
```

**Comment by Animenosekai** [comment]
Yea that's a problem from googletrans ( ssut/py-googletrans#234 ) and we could try to solve it but since Google changed their method of authenticating a user and managing sessions (the JSON RPC one we are using for `GoogleTranslate`) I don't think that it will work

**Comment by NawtJ0sh** [comment]
Hey guys, have you tested https://github.com/Animenosekai/translate/blob/main/translatepy/translators/google.py#L89 with the same text you want to translate to english, then tested it on the actual site, to see if it returns the same result?? Am I doing something wrong or does it do that for you too?

text:

كانت الحياة هناك ، على ما يبدو حلما ، على وشك أن تتحول إلى كابوس. "(وقفة درامية)" مرحبًا يا رفاق! لقد وجدت للتو طريقة جديدة رائعة لحلاقة شعر خصلاتي!

actual site:

Life there, apparently a dream, was about to turn into a nightmare. (dramatic pause) Hey guys! I just found a great new way to shave my tresses!

python module:

Life was there, apparently a dream, about to turn into a nightmare."(Dramatic pause)" Hello you guys!I just found a wonderful new way to shave my hair!

**Comment by Animenosekai** [comment]
Sorry 🙏

Please make another issue as this one is not related to `gtoken`

**Comment by Animenosekai** [comment]
@NawtJ0sh 

Sorry 🙏

Please make another issue as this one is not related to `gtoken`

**Comment by ZhymabekRoman** [comment]
> Google changed their method of authenticating a user and managing session


Ah, in that case maybe it makes sense to remove gtoken from translatepy completely? Or maybe make the old implementation separately in GoogleTranslateV3?

**Comment by Animenosekai** [comment]
> > Google changed their method of authenticating a user and managing session
> 
> Ah, in that case maybe it makes sense to remove gtoken from translatepy completely? Or maybe make the old implementation separately in GoogleTranslateV3?

I thought it would be fine to keep it, knowing that it will just raise an exception which will be catched.

Also, if this one is still on `googletrans` it should mean that it is still possible to use it in some way so why not keep it and if it works good if not well too bad it will just fall back to another endpoint
