### ISSUE TITLE
Bing & Deepl translators seem to be unable to get the correct JSON

### ISSUE THREAD

**Issue by Arludesi** [Animenosekai/translate#30]
Hi all,
I had tried to use the bing\deepl\google service, and only the google service can get the result, however the result text doesn't match the website shows... :(
Test code like this:
```
#from translatepy.translators.deepl import DeeplTranslate
from translatepy.translators.bing import BingTranslate
#from translatepy.translators.google import GoogleTranslate

#GoogleTranslate().translate('测试用例','en')
BingTranslate().translate('测试用例','en')
#DeeplTranslate().translate('测试用例','en')
```
And bing and deepl returned the same JSON error like this:
```
JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
It seems pointing the requests post isn't working correctly...?

**Comment by ZhymabekRoman** [comment]
Which version of translatepy are you using? Try downloading the latest version from the GitHub repository

**Comment by Arludesi** [comment]
> Which version of translatepy are you using? Try downloading the latest version from the GitHub repository:
> `pip install --upgrade git+https://github.com/Animenosekai/translate`

The translatepy version is updated to 2.1, and another error poped up...
`ModuleNotFoundError: No module named 'translatepy.utils'`

**Comment by Arludesi** [comment]
Maybe the reason is I installed the library in conda...?

https://user-images.githubusercontent.com/84886962/134635454-13c5c297-6069-4c71-af88-1049e71f0816.mp4

**Comment by Animenosekai** [comment]
> Maybe the reason is I installed the library in conda...?
> 
>  20210924_152333.mp4

Maybe, what is inside the installation folder? (`D:\ProgramData\Anaconda3\envs\selenium\lib\site-packages\translatepy`)

**Comment by Arludesi** [comment]
> > Maybe the reason is I installed the library in conda...?
> > 20210924_152333.mp4
> 
> Maybe, what is inside the installation folder? (`D:\ProgramData\Anaconda3\envs\selenium\lib\site-packages\translatepy`)

Like this:
![capture_20210924154124](https://user-images.githubusercontent.com/84886962/134637168-1da9b192-c4ce-4c93-b9bd-645e79c4ad87.png)

**Comment by Animenosekai** [comment]
> > > Maybe the reason is I installed the library in conda...?
> > > 20210924_152333.mp4
> > 
> > 
> > Maybe, what is inside the installation folder? (`D:\ProgramData\Anaconda3\envs\selenium\lib\site-packages\translatepy`)
> 
> Like this:
> ![capture_20210924154124](https://user-images.githubusercontent.com/84886962/134637168-1da9b192-c4ce-4c93-b9bd-645e79c4ad87.png)

Yes, that's what I thought, all of the folders are missing, maybe a bug from conda?

**Comment by Animenosekai** [comment]
Maybe try to `git clone` manually the repo and replace all of the files with the cloned one

**Comment by Arludesi** [comment]
> Maybe try to `git clone` manually the repo and replace all of the files with the cloned one

Allright....
When I install translatepy from clone, the same error `JSONDecodeError: Expecting value: line 1 column 1 (char 0)` comes again...
Will the json library version cause this crash? or the python version?
My current conda json version == 2.0.9, and python == 3.6

**Comment by Arludesi** [comment]
> > Maybe try to `git clone` manually the repo and replace all of the files with the cloned one
> 
> Allright....
> When I install translatepy from clone, the same error `JSONDecodeError: Expecting value: line 1 column 1 (char 0)` comes again...
> Will the json library version cause this crash? or the python version?
> My current conda json version == 2.0.9, and python == 3.6

Maybe worse, I try to use the basic `Translator()`, and it returns  `ValueError: No service has returned a valid result` to me :(
