### ISSUE TITLE
pip does not match github code?

### ISSUE THREAD

**Issue by davidmartinrius** [Animenosekai/translate#33]
Hello, I installed this package in my environment. I was trying to use translate_html but it does not exist in the current pip version. Is possible that needs to update the code in pip? Or am I doing something wrong?

I already executed pip install --upgrade translatepy and I have got translatepy v2.1. Unfortunately translate_html method is not inside the code..

Could you help me to solve that?

Thank you!!

**Comment by ZhymabekRoman** [comment]
Hello, thanks for using translatepy. Currently version 2.2 is under development and testing, and not yet available in Pypi. You can download and install the latest version of translatepy directly from the GitHub repository using the command: 
`pip install --upgrade git+https://github.com/Animenosekai/translate`

**Comment by Animenosekai** [comment]
@davidmartinrius I plan on uploading v2.2 soon but as we need to finish fine-tuning things you can install the development version with git as explained by @ZhymabekRoman

**Comment by davidmartinrius** [comment]
Perfect guys!! Thank you so much!
