### ISSUE TITLE
What is the right way to specify dest lang as Chinese?

### ISSUE THREAD

**Issue by xrkk** [Animenosekai/translate#48]
```py
from translatepy.utils.request import Request
from translatepy.translators.google import GoogleTranslateV1

proxy_request = Request(proxy_urls=["127.0.0.1:10809"])
translator = GoogleTranslateV1(request=proxy_request)
print(translator.translate(txt, Language("zh-cn")).result)
```

With above code, exception occurs: 
```
translatepy.exceptions.UnknownLanguage: Couldn't recognize the given language (zh-cn)
Did you mean: czech (Similarity: 67.61%)?
```

I tried again with "zh-CN" or "Chinese", none of them worked!

**Comment by ZhymabekRoman** [comment]
> I tried again with "zh-CN" or "Chinese", none of them worked!

Try specify "zho", this is a workaround for this unfixed bug.

**Comment by Animenosekai** [comment]
Thank you for reporting this issue @xrkk 

Indeed, `zh-CN` wasn't in the `CODES` list.

199c566 should fix your problem!

**Comment by xrkk** [comment]
Yes, it worked! Thank you for your good work. Closing this issue.
