### ISSUE TITLE
DeepL translations not working

### ISSUE THREAD

**Issue by davidmartinrius** [Animenosekai/translate#51]
Today I installed a fresh translatepy. I tried to translate simple sentences with DeepL like: "Hola, ¿Cómo estás?" (means "Hello, how are you?") from spanish to english.

But DeepL never returns a response. It works properly with the other translators. As we know, DeepL works hard to prevent users use unofficial API.

Do you know if something changed in unofficial API?

Two months ago DeepL used to work. It did not work perfectly because when I sent more thant 3 or 4 request in little time it stopped working for a while. But at least it worked some times.

The thing is that now it is not going to work.

Please, could you check it out? 

Thank you!

**Comment by ZhymabekRoman** [comment]
I confirm, prepared a PR correcting this problem - #52

**Comment by davidmartinrius** [comment]
> I confirm, prepared a PR correcting this problem - #52

Perfect! I see the main deepL endpoint has changed in your commit. Thank you for fixing it!
