### ISSUE TITLE
Defining which translator to use from the CLI

### ISSUE THREAD

**Issue by yyy33** [Animenosekai/translate#53]
Can you support the command line

**Comment by ZhymabekRoman** [comment]
@yyy33, What do you mean exactly?

**Comment by Animenosekai** [comment]
@yyy33 It already supports command line access :

[Animenosekai/translate - README - In other applications/from the terminal](https://github.com/Animenosekai/translate#in-other-applicationsfrom-the-terminal)

[Animenosekai/translate - README - Interactive Shell (REPL)](https://github.com/Animenosekai/translate#interactive-shell-repl)

**Comment by yyy33** [comment]
> @yyy33 It already supports command line access :
> 
> [Animenosekai/translate - README - In other applications/from the terminal](https://github.com/Animenosekai/translate#in-other-applicationsfrom-the-terminal)
> 
> [Animenosekai/translate - README - Interactive Shell (REPL)](https://github.com/Animenosekai/translate#interactive-shell-repl)

Sorry my text was swallowed Can you support to specify what translation service to use on the command line instead of the default Google

**Comment by Animenosekai** [comment]
> Sorry my text was swallowed Can you support to specify what translation service to use on the command line instead of the default Google

Oh yea my bad.

So basically it doesn't use Google by default but the `Translator` class, which uses different translators at once.

I planned on doing something to be able to specify the translation service but forgot about it.

**Comment by Animenosekai** [comment]
I'm currently coding a way of getting a translator from a string (its name or module location).

Currently, at the step of translating the different aliases for the translators, we are soon going to see if this works 👍

**Comment by Animenosekai** [comment]
440e0cbda3acc2b31aa5ad05a0affc54322f683b should fix your issue ✨
