### ISSUE TITLE
Proxy Support

### ISSUE THREAD

**Issue by cefege** [Animenosekai/translate#64]
Please Add proxy support so we can decrease the chance of getting banned when translating from Google for example.

**Comment by Animenosekai** [comment]
We already have proxy support though 🤔

**Comment by Animenosekai** [comment]
Ohhhh I'm sorry I didn't document it, my bad.

To add proxies, you need to pass your own `Request` instance, with the proxies.

> Example

```python
from translatepy.utils.request import Request
from translatepy import Translator

t = Translator(request=Request(proxy_urls=["<your proxy>"]))
t.translate("Hello world", "Japanese")
```

**Comment by cefege** [comment]
Thanks, it's awesome proxies work.

  Can you please explain what are the differences between GoogleTranslateV1
and GoogleTranslateV2?

  Which one is the recommended method for large scale translation, more
stable?

  How does the program decide which to use if I select GoogleTranslate?
  For example if GoogleTranslateV1 fails, does it try with
GoogleTranslateV2?

Best Regards,

Mike
