### ISSUE TITLE
Bulk Translation support?

### ISSUE THREAD

**Issue by emendoza2** [Animenosekai/translate#66]
GoogleTrans supports bulk translation.
![image](https://user-images.githubusercontent.com/24651940/184498713-a7c80a61-8fd3-4277-af3a-839383d82889.png)
Can translatepy do the same? It could be improved from googletrans with parallelizing (googletrans does it sequentially I believe). Although implementing this outside the translatepy api is trivial, it would be nice and developer-friendly to allow this functionality by just passing a list to the `translate` method.

**Comment by Animenosekai** [comment]
I would need to see if it's really worth it.

For example, if there is an error during translation, I personally think that it's better for the developer to be able to decide how many times he wants to retry or handle the error.

But it might be a great idea as a lot of other translating libraries implement this feature 🤔

**Comment by Animenosekai** [comment]
Closing since it's coming in v3

Feel free to reply if you want to open it again !
