### ISSUE TITLE
Is the DeepL split text correct?

### ISSUE THREAD

**Issue by swfsql** [Animenosekai/translate#82]
I believe that deepl split text should splits the text into an array of text lines.

Currently it appears that the [regex](https://github.com/Animenosekai/translate/blob/18e008aa505387e9334ca7a985f21a6c0dd3f7f8/translatepy/translators/deepl.py#L22) doesn't splits by line, and the regex usage doesn't [change](https://github.com/Animenosekai/translate/blob/18e008aa505387e9334ca7a985f21a6c0dd3f7f8/translatepy/translators/deepl.py#L122) the `text` variable.

But I'm not sure if I'm confusing the calls to `LMT_split_into_sentences` vs `LMT_split_text` (I noticed that using deepl in the browser, it appears to use the later).

I made a test in the browser, translating "こんにちは世界" and "こんにちは" in two separated lines, and in case it helps, it made the calls:

An option and then a post request to `https://www2.deepl.com/jsonrpc?method=LMT_split_text`:
```json
{
    "jsonrpc":"2.0",
    "method" : "LMT_split_text",
    "params":{"texts":["こんにちは世界","こんにちは"],
    "commonJobParams":{"mode":"translate"},
    "lang":{
        "lang_user_selected":"JA",
        "preference":{
            "weight":/*..*/,
            "default":"default"}
        }
    },
    "id":/*..*/
}
```
With the response:
```json
{
    "jsonrpc":"2.0",
    "id":/*..*/,
    "result":{
        "lang":{"detected":"JA","isConfident":true,"detectedLanguages":{"JA":1.0}},
        "texts":[
            {"chunks":[{"sentences":[{"prefix":"","text":"\u3053\u3093\u306B\u3061\u306F\u4E16\u754C"}]}]},
            {"chunks":[{"sentences":[{"prefix":"","text":"\u3053\u3093\u306B\u3061\u306F"}]}]}
        ]
    }
}
```

Then an option and then a post request to `https://www2.deepl.com/jsonrpc?method=LMT_handle_jobs`:
```json
{
    "jsonrpc":"2.0",
    "method": "LMT_handle_jobs",
    "params":{
        "jobs":[
            {
                "kind":"default",
                "sentences":[{"text":"こんにちは世界","id":0,"prefix":""}],
                "raw_en_context_before":[],
                "raw_en_context_after":["こんにちは"],
                "preferred_num_beams":1
            },
            {
                "kind":"default",
                "sentences":[ {"text":"こんにちは","id":1, "prefix":""}],
                "raw_en_context_before":["こんにちは世界"],
                "raw_en_context_after":[],
                "preferred_num_beams":1
            }
        ],
        "lang":{"preference":{"weight":{},"default":"default"},"source_lang_computed":"JA","target_lang":"EN"},
        "priority":1,
        "commonJobParams":{"regionalVariant":"en-US","mode":"translate","browserType":1},
        "timestamp":/*..*/
    },
    "id":/*..*/
}
```

With the response:
```json
{
    "jsonrpc":"2.0","id":/*..*/,
    "result":{"translations":[
        {"beams":[{"sentences":[{"text":"Hello World","ids":[0]}],"num_symbols":3}],"quality":"normal"},
        {"beams":[{"sentences":[{"text":"Hello world","ids":[1]}],"num_symbols":3}],"quality":"normal"}],
    "target_lang":"EN","source_lang":"JA","source_lang_is_confident":false,"detectedLanguages":/*..*/}
}
```
(for some reason it incorrectly translated both lines to Hello World, but it gave a beam for each line)

I hope this helps in case there is something missing! (I would make more tests but I'm getting "Too Many Requests" error, so I guess my IP was banned for trying invalid requests).

**Comment by Animenosekai** [comment]
Thanks for reporting this issue !

Seems like #83 closed it. Let me know if you want to reopen 👍

**Comment by swfsql** [comment]
@Animenosekai Thanks!

On a new note, I think the regex is not being used, as it's return is not being stored in any variable, nor it's being used as a function return:

https://github.com/Animenosekai/translate/blob/11650ca1419d9cc500b619aed3a55617a85c0ed5/translatepy/translators/deepl.py#L122

**Comment by Animenosekai** [comment]
> @Animenosekai Thanks!
> 
> 
> 
> On a new note, I think the regex is not being used, as it's return is not being stored in any variable, nor it's being used as a function return:
> 
> 
> 
> https://github.com/Animenosekai/translate/blob/11650ca1419d9cc500b619aed3a55617a85c0ed5/translatepy/translators/deepl.py#L122

Oh that's right, I should look into it !
