### ISSUE TITLE
How to set timeout for Translate requesting?

### ISSUE THREAD

**Issue by shadu120** [Animenosekai/translate#89]
My server can't access Google, Bing, but Yandex is OK.

When I use this command It costs about 5 minutes to get result.

```python
from translatepy import Translator
translator = Translator()
translator.translate("Hello", "French")
```

This works fast!
```python
from translatepy.translators.yandex import YandexTranslate
YandexTranslate().translate('My name is John', 'French')
```

I know that translatepy is working with multiple engines. Does this code try all the engines one by one or at the same time with multi-threads?

I want to set a global request timeout to make it fail quickly, like this `t = Translator(request=Request(timeout=10))`

Any solution?

**Comment by ZhymabekRoman** [comment]
> Does this code try all the engines one by one or at the same time with multi-threads?

By default one at a time. You can set the `fast` argument to do multi-threaded translation. 

> I want to set a global request timeout to make it fail quickly

I have tested all possible solutions in my opinion and it seems to me that there is no solution yet.

**Comment by shadu120** [comment]
Thanks for your replying. It looks like a good way to set this. but, I can't impot `Session` from `from translatepy.utils.request `

```
from translatepy.utils.request import Session
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'Session' from 'translatepy.utils.request' (/Users/xxx/py3/lib/python3.11/site-packages/translatepy/utils/request.py)

```
This is my translatepy version.

```bash
~ % python -c "import translatepy; print(translatepy.__version__)"
translatepy v2.3
```

I tried another way:

```python
from translatepy import Translate
from requests import Session
s=Session()
s.timeout=10
t = Translate(session=s)
```

Got error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: Translate.__init__() got an unexpected keyword argument 'session'
```


Actually, there is no parameter names session for `Translate`
<img width="442" alt="image" src="https://github.com/Animenosekai/translate/assets/3023471/c8ba5721-38ef-4b4b-800e-9bb484017740">

**Comment by shadu120** [comment]
I've no privilege to reopen this issue. @Animenosekai

**Comment by Animenosekai** [comment]
> I've no privilege to reopen this issue. @Animenosekai

Riiiight sorry I forgot let me reopen this real quick

**Comment by Animenosekai** [comment]
@shadu120 

> This is my translatepy version.

Try installing the `new-models` branch version, as explained in https://github.com/Animenosekai/translate/issues/85#issuecomment-1658533949 I'll try to merge it soon.

To install the `new-models` branch version, you need to have `git` installed on your computer and run :

```bash
pip install --upgrade git+https://github.com/Animenosekai/translate.git@new-models
```

**Comment by Animenosekai** [comment]
Also this is the code I wrote to quickly test the session system :

```python
from translatepy import Translate
from translatepy.utils.request import Session
s = Session()
s.timeout = 10
t = Translate(session=s)
print(t.translate("Hello world", "Japanese"))
```

```bash
$ translatepy --version
translatepy v3.0(alpha) # output
```

**Comment by shadu120** [comment]
Thans! Great job!
